POST https://node-teste-web.onrender.com/videos
Content-type: application/json

{
  "titulo": "Naruto Classic",
  "descricao": "Temporada 1",
  "duracao": 300
}

###

GET https://node-teste-web.onrender.com/videos

###
PUT https://node-teste-web.onrender.com/74ea1bdd-ed81-4c52-84ee-359f8a090718
Content-type: application/json

{
  "titulo": "Equalizer II",
  "descricao": "Capitulo final",
  "duracao": 140
}

###
DELETE https://node-teste-web.onrender.com/bc444ed5-f55f-480e-84f5-fb43d9c23d2f